micronaut:
  http:
    client:
#      read-timeout: 1s
  server:
    port: 8904
  application:
    name: api-gateway-service

netty:
  default:
    allocator:
      max-order: 3

consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"

#eureka:
#  client:
#    registration:
#      enabled: true
#    defaultZone: "${EUREKA_HOST:localhost}:${EUREKA_PORT:8900}"