micronaut:
  server:
    port: 8901
  application:
    name: book-service
datasources:
  default:
    url: jdbc:h2:mem:bookdb
    driverClassName: org.h2.Driver
    username: sa
#    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
netty:
  default:
    allocator:
      max-order: 3

jpa:
  default:
    entity-scan:
      packages: 'io.medveckis.model'
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
      show_sql: true

consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"

#eureka:
#  client:
#    registration:
#      enabled: true
#    defaultZone: "${EUREKA_HOST:localhost}:${EUREKA_PORT:8900}"